version: "3"
services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - .:/home/api
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - 5000:5000
